//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.ASModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgriculturalStatistic
    {
        public int Id { get; set; }
        public Nullable<double> ArableLandArea { get; set; }
        public Nullable<double> FertilizerQuantity { get; set; }
        public Nullable<double> PotashFertilizerQuantity { get; set; }
        public Nullable<double> TotalGrainOutput { get; set; }
        public Nullable<double> CattleCount { get; set; }
        public Nullable<double> PigCount { get; set; }
        public Nullable<double> SheepCount { get; set; }
        public Nullable<double> PoultryCount { get; set; }
        public int Year { get; set; }
        public int CountyId { get; set; }
        public int ProvinceId { get; set; }
    
        public virtual County County { get; set; }
        public virtual Province Province { get; set; }
    }
}
